### ISSUE TITLE
Doesn't recognize 10 minutes of e-mails

### ISSUE THREAD

**Issue by Dropelikeit** [jprangenbergde/temporary-email-detection#3]
I noticed that some temporary e-mail addresses are not recognized by the detection. For example, "10 minute mail" are often not detected.

Example: https://10minutemail.com/10MinuteMail/index.html?dswid=4307

Here the detection says that it is a normal email address, but it is not permanently accessible due to its 10 minute limit.

**Comment by jprangenbergde** [comment]
Thanks @Dropelikeit, i will implement the specified emails.

**Comment by jprangenbergde** [comment]
Fixed.
